package com.calculartipodecambio.tipocambio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datosClientes implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Tipo de Canal ")
	private java.lang.String vCanal;
	@org.kie.api.definition.type.Label(value = "Día Feriado")
	private java.lang.String vFeriado;
	@org.kie.api.definition.type.Label(value = "Mercado Cerrado")
	private java.lang.Integer vHora;
	@org.kie.api.definition.type.Label(value = "Segmento del cliente")
	private java.lang.Integer vSegmento;
	@org.kie.api.definition.type.Label(value = "Valor Spread Personalizado")
	private java.lang.Integer vSpreadPersonalizado;
	@org.kie.api.definition.type.Label(value = "Tipo Tasa de Cambio")
	private java.lang.Double vTipoCambioC;
	@org.kie.api.definition.type.Label(value = "Tipo de Operación")
	private java.lang.String vTipoOperacion;

	public datosClientes() {
	}

	public java.lang.String getvCanal() {
		return this.vCanal;
	}

	public void setvCanal(java.lang.String vCanal) {
		this.vCanal = vCanal;
	}

	public java.lang.String getvFeriado() {
		return this.vFeriado;
	}

	public void setvFeriado(java.lang.String vFeriado) {
		this.vFeriado = vFeriado;
	}

	public java.lang.Integer getvHora() {
		return this.vHora;
	}

	public void setvHora(java.lang.Integer vHora) {
		this.vHora = vHora;
	}

	public java.lang.Integer getvSegmento() {
		return this.vSegmento;
	}

	public void setvSegmento(java.lang.Integer vSegmento) {
		this.vSegmento = vSegmento;
	}

	public java.lang.Integer getvSpreadPersonalizado() {
		return this.vSpreadPersonalizado;
	}

	public void setvSpreadPersonalizado(java.lang.Integer vSpreadPersonalizado) {
		this.vSpreadPersonalizado = vSpreadPersonalizado;
	}

	public java.lang.Double getvTipoCambioC() {
		return this.vTipoCambioC;
	}

	public void setvTipoCambioC(java.lang.Double vTipoCambioC) {
		this.vTipoCambioC = vTipoCambioC;
	}

	public java.lang.String getvTipoOperacion() {
		return this.vTipoOperacion;
	}

	public void setvTipoOperacion(java.lang.String vTipoOperacion) {
		this.vTipoOperacion = vTipoOperacion;
	}

	public datosClientes(java.lang.String vCanal, java.lang.String vFeriado,
			java.lang.Integer vHora, java.lang.Integer vSegmento,
			java.lang.Integer vSpreadPersonalizado,
			java.lang.Double vTipoCambioC, java.lang.String vTipoOperacion) {
		this.vCanal = vCanal;
		this.vFeriado = vFeriado;
		this.vHora = vHora;
		this.vSegmento = vSegmento;
		this.vSpreadPersonalizado = vSpreadPersonalizado;
		this.vTipoCambioC = vTipoCambioC;
		this.vTipoOperacion = vTipoOperacion;
	}

}