package com.calculartipodecambio.tipocambio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datosSalidaSegmento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "vSpreadSegmento")
	private java.lang.Double vSpreadSegmento;

	public datosSalidaSegmento() {
	}

	public java.lang.Double getvSpreadSegmento() {
		return this.vSpreadSegmento;
	}

	public void setvSpreadSegmento(java.lang.Double vSpreadSegmento) {
		this.vSpreadSegmento = vSpreadSegmento;
	}

	public datosSalidaSegmento(java.lang.Double vSpreadSegmento) {
		this.vSpreadSegmento = vSpreadSegmento;
	}

}