package com.calculartipodecambio.tipocambio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datosSalidaMercado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "vSpreadMercado")
	private java.lang.Double vSpreadMercado;

	public datosSalidaMercado() {
	}

	public java.lang.Double getvSpreadMercado() {
		return this.vSpreadMercado;
	}

	public void setvSpreadMercado(java.lang.Double vSpreadMercado) {
		this.vSpreadMercado = vSpreadMercado;
	}

	public datosSalidaMercado(java.lang.Double vSpreadMercado) {
		this.vSpreadMercado = vSpreadMercado;
	}

}