package com.calculartipodecambio.tipocambio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datosSalida implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Tipo de cambio de cliente")
	private java.lang.Double vTipoCambio;

	public datosSalida() {
	}

	public java.lang.Double getvTipoCambio() {
		return this.vTipoCambio;
	}

	public void setvTipoCambio(java.lang.Double vTipoCambio) {
		this.vTipoCambio = vTipoCambio;
	}

	public datosSalida(java.lang.Double vTipoCambio) {
		this.vTipoCambio = vTipoCambio;
	}

}