package com.calculartipodecambio.tipocambio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datosSalidaFeriado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "vSpreadFeriado")
	private java.lang.Double vSpreadFeriado;

	public datosSalidaFeriado() {
	}

	public java.lang.Double getvSpreadFeriado() {
		return this.vSpreadFeriado;
	}

	public void setvSpreadFeriado(java.lang.Double vSpreadFeriado) {
		this.vSpreadFeriado = vSpreadFeriado;
	}

	public datosSalidaFeriado(java.lang.Double vSpreadFeriado) {
		this.vSpreadFeriado = vSpreadFeriado;
	}

}