package com.calculartipodecambio.tipocambio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datosSalidaCanal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "vSpreadCanal")
	private java.lang.Double vSpreadCanal;

	public datosSalidaCanal() {
	}

	public java.lang.Double getvSpreadCanal() {
		return this.vSpreadCanal;
	}

	public void setvSpreadCanal(java.lang.Double vSpreadCanal) {
		this.vSpreadCanal = vSpreadCanal;
	}

	public datosSalidaCanal(java.lang.Double vSpreadCanal) {
		this.vSpreadCanal = vSpreadCanal;
	}

}